### ISSUE TITLE
[Tracking] Improve Python generator EDSL

### ISSUE THREAD

**Issue by sampsyo** [cucapra/calyx#1240]
The first version of the weird little Python EDSL for generating Calyx programs in #1229 leaves a lot of gaps! Here are some ideas for what to do to it next; please feel free to add.

- [ ] Convenience for more control operators (`par`, `while`, `if`). (It is already allowed to construct the AST explicitly.) `par` should use Python `sets.
- [ ] More coverage of stdlib components, and a way to construct user-defined (non-stdlib) components.
- [ ] Continuous assignments. Probably do something like `with comp.continuous:`, or just have this be the default when you're not in a `with`.
- [ ] @cgyurgyik's idea to add simple correctness checks for well-known stdlib cells: for example, throw an error when assigning to an unknown port. (There should be an easy way to declare the set of known ports for a given component.)
- [ ] Explore @rachitnigam's idea re. swapping out the "backend" to generate in-memory IR instead of serializing the AST to text.
- [ ] Documentation page.
