### ISSUE TITLE
Tutorial Checklist

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#1513]
Tracking the low-level tasks that need to be done before the tutorial:
- [x] Dry-run
  - [x] `x86` machines ([Havarti](https://capra.cs.cornell.edu/private/havarti.html))
  - [x] M1 mac ([Parmigiano server](https://capra.cs.cornell.edu/private/parmigiano.html))
  - [x] Manual Installation
- [ ] Docker Issues
  - [x] Make sure people can `docker pull` the GHCR image
  - [x] Ensure that `fud check` reports that things are correctly installed
  - [x] Ensure `runt -i 'core | mrxl'` works
  - [x] Make sure that `fud` commands within the docker container work outside the `calyx` repo (no relative paths)
  - [x] Install `mrxl-data` binary
  - [x] Install emacs and vim in the Docker
  - [x] #1559 
- [ ] Slide deck
  - [x] Assign speakers to sections
  - [x] Make slides
  - [x] Practice run through
  - [x] Add a PDF version and link to it from the tutorial

## Final Checklist
We should do these things after the dry run has concluded

- [x] Release latest version of docker containers for `x86` and `arm`
- [ ] Check that we have audio setup for virtual speakers
- [ ] Proof-read the documentation and fix any broken links
- [ ] Finalize slides

**Comment by anshumanmohan** [comment]
Should the Docker have `vim` or some other text editor installed?

**Comment by anshumanmohan** [comment]
I think I was the only person who could not pull Docker, and now I can too. Weird. Sorry about the stress. Checking that box.

**Comment by rachitnigam** [comment]
Argh, sorry we missed this. How about we put up a note on the slide saying "please install and configure your favorite editor" once people install the docker image?

**Comment by rachitnigam** [comment]
The website now has a link the PDF (right before the schedule). Once someone verifies the link, we can close this issue

**Comment by anshumanmohan** [comment]
Can confirm that the links works

**Comment by anshumanmohan** [comment]
Re the text editor:

A little odd to be sure, but yeah this may be the band-aid solution. To make it a slightly nicer band-aid, you could give them the necessary `apt` incantations on the slides. May want to check that they work (e.g. that `sudo` is not required...)

Just to be clear, since we're closing in on this: cool if this gets added to your list as you make the initial slides?
