### ISSUE TITLE
[Relay] Toward a working VGG Net (continued).

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/calyx#369]
## VGG Net
- [x] Change go-done interface to `invoke`ables. This requires [Dahlia #340](https://github.com/cucapra/dahlia/pull/340). (#379)
- [X] Re-add the rest of the supported Relay functions. (#396)
- [X] Support constants (#406)
- [x] Support `std_exp` round 2; finish `nn.softmax` implementation. This should be the last piece of lowering the entire VGG Net to FuTIL. (#396, #404, #490) 

## Code Improvements
- [x] Fix the test suite. Tests for individual Relay function calls (e.g. `nn.relu`) should be part of the integration test suite. However, a few unit tests should be added to ensure that any changes to Calyx affecting the Relay frontend will cause notice. (#396)
- [x] Fix FuTIL AST. Most of the work here should be done in #368.
- [X] Clean up `frontends/relay/example.py`. (#406)
- [x] Update installation. Currently missing `antlr-4-python3-runtime` pip install. Move to main Calyx documentation. (#408)

**Comment by cgyurgyik** [comment]
Status update: Blocked on a working `softmax` or `exp` operator, as well as synthesizable `{mult, div, mod}_pipe`s for fixed point.
